camera:
  username: "voice4pimd"
  password: "voice4pimd"
  ip: "10.12.130.50"
  stream: "stream2"
  gstreamer_pipeline: "protocols=tcp latency=60 ! rtph264depay ! h264parse ! nvv4l2decoder ! nvvidconv ! video/x-raw, format=BGRx ! videoconvert ! appsink sync=false max-buffers=1 drop=true"
  gstreamer: true

microphone:
  gstreamer_pipeline: "latency=60 do-rtsp-keep-alive=true ! application/x-rtp,media=audio,encoding-name=PCMA,clock-rate=8000 ! rtppcmadepay ! alawdec ! audioconvert ! audioresample ! audio/x-raw,format=F32LE,channels=1,rate=8000 ! appsink name=appsink sync=false max-buffers=10 drop=true"
  channels: 1 # Ensure this matches the pipeline's channel count

sensor_array:
  pipeline: "default"